### ISSUE TITLE
ccache fails on long path names. 

### ISSUE THREAD

**Issue by ravarora** [nagayasu-shinya/ccache-win64#2]
ccache fails if the path to .o files generated by cmake is long. It fails with the following error 
"ccache: error: Failed to create temporary file for <long path file name> no such file or directory"

**Comment by nagayasu-shinya** [comment]
MAX_PATH is 260 in Windows, is your files length more?

**Comment by ravarora** [comment]
Yes. We are using cmake and the intermediate files generated by cmake are going beyond 260 limit.

**Comment by nagayasu-shinya** [comment]
It seems like that ccache on windows is limited file name length less 260 from following code;
https://github.com/ccache/ccache/blob/a0f7c10567b041079eef7aab8055091c79b4049b/src/util.c#L113

**Comment by ravarora** [comment]
Could this be overridden if i set an environment variable in Windows?

**Comment by nagayasu-shinya** [comment]
I'm afraid not. It's defined when ccache.exe is built by preprocessor.
Could you open issue at the original repository?
This my repository's program is just only build from ccache source code without anything change.

**Comment by ravarora** [comment]
Thanks Nagayasu. I will open an issue on the main repo. Closing this issue now.
