### ISSUE TITLE
Have you tried to get upstream to adopt this binary?

### ISSUE THREAD

**Issue by luzpaz** [nagayasu-shinya/ccache-win64#4]

**Comment by nagayasu-shinya** [comment]
No.

**Comment by luzpaz** [comment]
@nagayasu-shinya would you perhaps be interested in keeping this binary up to date so that it could be used in a windows package manager ? (ref: https://github.com/chocolatey-community/chocolatey-package-requests/issues/626 )

**Comment by nagayasu-shinya** [comment]
sorry I dont know a lot about windows package maneger...
It works on power shell?

**Comment by luzpaz** [comment]
Indeed.
```
Windows 7+ / Windows Server 2003+
PowerShell v2+ (Not PowerShell Core yet though)
.NET Framework 4+ (the installation will attempt to install .NET 4.0 if you do not have it installed)
That's it! All you need is choco.exe (that you get from the installation scripts) and you are good to go! No Visual Studio required.
```
source: https://chocolatey.org/install

**Comment by jrosdahl** [comment]
(ccache upstream developer here)

I don't use MinGW (or Windows) myself, but I/we regularly check that it works to cross-compile ccache with the i686-w64-mingw32 compiler. I can add a build check for x86_64-w64-mingw32 as well.

I'm willing to *consider* publishing prebuilt mingw binaries (cross-compiled on Linux) as well alongside the source code release archives, but they won't be tested in any way before the release. Does that sound like a good idea? If so, should it be only a 64-bit version, only a 32-bit version or both?

**Comment by luzpaz** [comment]
@jrosdahl both 32 and 64 bit make sense. Feel free to let us know when the prebuilt binaries are available, on https://github.com/chocolatey-community/chocolatey-package-requests/issues/626  
Thanks!

**Comment by jrosdahl** [comment]
> Feel free to let us know when the prebuilt binaries are available, 

Sure. I'm not promising anything, though.

We (the ccache project) are currently discussing the future of ccache Windows support. One major problem with the Windows/MinGW support is that we test that it's possible to build ccache with MinGW but the test suite is not run, so it's very possible that new versions could introduce runtime bugs that are unknown at the time of release.

**Comment by nagayasu-shinya** [comment]
Hi @jrosdahl 

> I'm willing to consider publishing prebuilt mingw binaries (cross-compiled on Linux) as well alongside the source code release archives, but they won't be tested in any way before the release. Does that sound like a good idea? 

It sounds good. I think It helps many Windows user.

>  One major problem with the Windows/MinGW support is that we test that it's possible to build ccache with MinGW but the test suite is not run, so it's very possible that new versions could introduce runtime bugs that are unknown at the time of release.

Is the test suite "https://github.com/ccache/ccache/tree/master/test/suites" ?
If I remember right, it runs on MINGW Expectedly.

**Comment by jrosdahl** [comment]
See also ccache/ccache#447.

**Comment by nagayasu-shinya** [comment]
Thanks. Let's discuss at the issue.
